package br.com.example.collect.model;

import java.util.List;

import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface CollectRepository extends CrudRepository<Collect, Long>, CollectRepositoryCustom {

	/**
	 * Query method generated by spring-data
	 * @param location
	 * @return
	 */
	List<Collect> findByLocation(String location);
}
